services:
  - type: web
    name: telegram-stories-bot
    runtime: python
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: your_bot_token_here
      - key: WEBHOOK_URL
        value: https://your-service-name.onrender.com/webhook
      - key: PORT
        value: 8000
